from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 723)
        MainWindow.setMinimumSize(QtCore.QSize(700, 723))
        MainWindow.setMaximumSize(QtCore.QSize(3000, 3000))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icons8-justify-right-alignment-paragraph-setting-text-layout-position-format-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEdite = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdite.setObjectName("menuEdite")
        self.menuFormat = QtWidgets.QMenu(parent=self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionnew = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/icons8-new-67.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionnew.setIcon(icon1)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/icons8-open-sign-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionopen.setIcon(icon2)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/icons8-save-94.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionsave.setIcon(icon3)
        self.actionsave.setObjectName("actionsave")
        self.actionprint = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/icons8-send-to-printer-16.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionprint.setIcon(icon4)
        self.actionprint.setObjectName("actionprint")
        self.actionprint_previe = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/icons8-image-preview-thumbnail-frame-template-design-layout-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionprint_previe.setIcon(icon5)
        self.actionprint_previe.setObjectName("actionprint_previe")
        self.actionexport_PDF = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/icons8-pdf-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionexport_PDF.setIcon(icon6)
        self.actionexport_PDF.setObjectName("actionexport_PDF")
        self.actionQuite = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/icons8-exit-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionQuite.setIcon(icon7)
        self.actionQuite.setObjectName("actionQuite")
        self.actionundo = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/icons8-undo-80.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionundo.setIcon(icon8)
        self.actionundo.setObjectName("actionundo")
        self.actionredo = QtGui.QAction(parent=MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/icons8-right-2-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionredo.setIcon(icon9)
        self.actionredo.setObjectName("actionredo")
        self.actioncut = QtGui.QAction(parent=MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/icons8-cut-paper-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actioncut.setIcon(icon10)
        self.actioncut.setObjectName("actioncut")
        self.actioncopy = QtGui.QAction(parent=MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/icons8-one-page-up-80.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actioncopy.setIcon(icon11)
        self.actioncopy.setObjectName("actioncopy")
        self.actionpaste = QtGui.QAction(parent=MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icon/icons8-paste-80.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionpaste.setIcon(icon12)
        self.actionpaste.setObjectName("actionpaste")
        self.actionBold = QtGui.QAction(parent=MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icon/icons8-bold-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionBold.setIcon(icon13)
        self.actionBold.setObjectName("actionBold")
        self.actionItallic = QtGui.QAction(parent=MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icon/icons8-italic-67.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionItallic.setIcon(icon14)
        self.actionItallic.setObjectName("actionItallic")
        self.actionUnderline = QtGui.QAction(parent=MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icon/icons8-underline-80.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionUnderline.setIcon(icon15)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionLeft = QtGui.QAction(parent=MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icon/icons8-double-left-80.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLeft.setIcon(icon16)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtGui.QAction(parent=MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icon/icons8-right-button-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionRight.setIcon(icon17)
        self.actionRight.setObjectName("actionRight")
        self.actionJustify = QtGui.QAction(parent=MainWindow)
        self.actionJustify.setIcon(icon)
        self.actionJustify.setObjectName("actionJustify")
        self.actionFont = QtGui.QAction(parent=MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icon/icons8-font-size-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionFont.setIcon(icon18)
        self.actionFont.setObjectName("actionFont")
        self.actionColor = QtGui.QAction(parent=MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icon/icons8-color-wheel-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionColor.setIcon(icon19)
        self.actionColor.setObjectName("actionColor")
        self.actioncenter = QtGui.QAction(parent=MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("icon/icons8-center-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actioncenter.setIcon(icon20)
        self.actioncenter.setObjectName("actioncenter")
        self.menufile.addAction(self.actionnew)
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionsave)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionprint)
        self.menufile.addAction(self.actionprint_previe)
        self.menufile.addAction(self.actionexport_PDF)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionQuite)
        self.menuEdite.addAction(self.actionundo)
        self.menuEdite.addAction(self.actionredo)
        self.menuEdite.addSeparator()
        self.menuEdite.addAction(self.actioncut)
        self.menuEdite.addAction(self.actioncopy)
        self.menuEdite.addAction(self.actionpaste)
        self.menuFormat.addAction(self.actionBold)
        self.menuFormat.addAction(self.actionItallic)
        self.menuFormat.addAction(self.actionUnderline)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionLeft)
        self.menuFormat.addAction(self.actionRight)
        self.menuFormat.addAction(self.actionJustify)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addAction(self.actionColor)
        self.menuFormat.addAction(self.actioncenter)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEdite.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.toolBar.addAction(self.actionnew)
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addAction(self.actionexport_PDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionundo)
        self.toolBar.addAction(self.actionredo)
        self.toolBar.addAction(self.actioncut)
        self.toolBar.addAction(self.actioncopy)
        self.toolBar.addAction(self.actionpaste)
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItallic)
        self.toolBar.addAction(self.actionUnderline)
        self.toolBar.addAction(self.actionLeft)
        self.toolBar.addAction(self.actionRight)
        self.toolBar.addAction(self.actionFont)
        self.toolBar.addAction(self.actionColor)
        self.toolBar.addAction(self.actioncenter)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuite)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "notepad-shab-bit"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuEdite.setTitle(_translate("MainWindow", "Edite"))
        self.menuFormat.setTitle(_translate("MainWindow", "Format"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionnew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionprint.setText(_translate("MainWindow", "print"))
        self.actionprint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionprint_previe.setText(_translate("MainWindow", "print previe"))
        self.actionprint_previe.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionexport_PDF.setText(_translate("MainWindow", "export PDF"))
        self.actionQuite.setText(_translate("MainWindow", "Quite"))
        self.actionundo.setText(_translate("MainWindow", "undo"))
        self.actionundo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionredo.setText(_translate("MainWindow", "redo"))
        self.actionredo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actioncut.setText(_translate("MainWindow", "cut"))
        self.actioncut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actioncopy.setText(_translate("MainWindow", "copy"))
        self.actioncopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionpaste.setText(_translate("MainWindow", "paste"))
        self.actionpaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionItallic.setText(_translate("MainWindow", "Itallic"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.actionJustify.setText(_translate("MainWindow", "Justify"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actioncenter.setText(_translate("MainWindow", "center"))